### ISSUE TITLE
Первая версия

### ISSUE THREAD

**Issue by aiiddqd** [systemo-biz/todo-cp#1]
- за основу берем плагин https://github.com/systemo-biz/todo-comments-cp - он уже умеет 80% того что нужно
- меняем имя шорткода и прочие ключи, чтобы плагины не пересекались и могли работать в рамках одной страницы
- убираем галочку "на контроле"
- реализуем поле добавления пункта в список (пользователь может добавить пункт в список) как обычно это делается в чек листах
- пользователь может добавить несколько пунктов и упорядочить их по иерархии
- при закрытии чек поинта должна проставляться дата закрытия в мету done_time_item_cp и дата закрытия должна показываться в тексте чек поинта
- опция "Скрыть/показать закрытые пункт", при нажатии скрывает или показывает закрытые пункты
- опция "Показать историю закрытий" выводит порядок закрытий через thikbox по урл типа (post?view=list_done_history) (пример логики https://github.com/systemo-biz/casepress/blob/master/cp-includes/cases/includes/visits/visits_check/view.php )

**Comment by dmnbars** [comment]
В каком формате данные должны выводиться в истории закрытия?
https://github.com/dmnbars/todo-cp

Так же, если подключен https://github.com/systemo-biz/todo-comments-cp, то не работают js скрипты, но что-то разобраться в чем именно проблема я не могу. 
Может быть. подскажите, в каком направлении думать?

**Comment by dmnbars** [comment]
Исправил. Теперь работает и вместе с casepress-comment-control.

**Comment by aiiddqd** [comment]
дай ссылку на демо и как проверить?
я гляну и тогда мб лучше пойму вопрос

**Comment by dmnbars** [comment]
Демо можно глянуть тут:
http://dmnbars.esy.es/test/movie/темный-рыцарь-возрождение-легенды

**Comment by aiiddqd** [comment]
иерархия не работает

**Comment by aiiddqd** [comment]
перетащил пункты - ничего не сохранилось

**Comment by dmnbars** [comment]
иерархия имеется ввиду, возможность создания подпунктов?

Да, пункты, почему-то перестали сохраняться. Переделаю)

**Comment by aiiddqd** [comment]
смотри демо скрипта http://johnny.github.io/jquery-sortable/

там есть возможность иерархической сортировки.

создавать пункты можно и в один уровень. но потом перетаскивать надо как подпункты

**Comment by dmnbars** [comment]
ага, понял, сделаю

**Comment by aiiddqd** [comment]
получается?

**Comment by dmnbars** [comment]
Не совсем.
При отсутсвии вложенности, сохранение позиции работает.
Сейчас сделал возможность делать пункты подпунктами (перетаскиванием), осталось перепистаь сохранение позиции, что бы работало и с подпунктами.

**Comment by dmnbars** [comment]
Сделал.

**Comment by aiiddqd** [comment]
код залей сюда https://github.com/systemo-biz/todo-cp

**Comment by aiiddqd** [comment]
поле добавления оформи нормально
чтобы на всю длину была http://getbootstrap.com/css/#forms

**Comment by dmnbars** [comment]
Поправил.

**Comment by aiiddqd** [comment]
ок, закрываем
сразу можно вторую версию начать
